default_django/urls.py
from django.contrib import admin
# from django.conf.urls import url, include
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('default_page.urls')),
    path('', include('default_users_app.urls')),
    path('', include('polls.urls')),
    path('', include('training.urls')),
]

default_page/urls.py
# from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'default_page'
urlpatterns = [
    path('', views.index, name='index'),
    path('showall/', views.showall, name='showall'),
    path('detail/<int:subject_id>', views.detail, name='detail'),
]

default_users_app/urls.py
from django.conf.urls import url, include
from django.urls import path, include
from . import views
from django.contrib.auth import views as django_default_views

app_name = 'default_users_app'
urlpatterns = [
    path('termin', views.termin, name='termin'),
    path('register', views.register_view, name='register'),
    path('profile', views.profile_user_view, name='profile'),
    path('login', django_default_views.LoginView.as_view(template_name='default_users_app/login.html'), name='login'),
    path('logout', django_default_views.LogoutView.as_view(template_name='default_users_app/logout.html'), name='logout'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('index_question/', views.index_question, name='index_question')
]

default_page/models.py
from django.db import models

class TreiningTopic(models.Model):
    trening_topic = models.CharField(max_length=50)

    def __str__(self):
        return self.trening_topic

class TreningChoice(models.Model):
    treningChoiceQuestion = models.ForeignKey(TreiningTopic, on_delete=models.CASCADE)
    treningChoiceDescribe = models.CharField(max_length = 200)

    def __str__(self):
        return self.treningChoiceDescribe

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=20)
    published_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    choice_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=20)
    def __str__(self):
        return self.choice_text



# Dodanie metod __str__() do twoich modeli jest ważne, nie tylko dla twojej własnej wygody, gdy używasz interaktywnego
# prompta, ale także dlatego, że reprezentacje obiektów są używane w automatycznie generowanym panelu administracyjnym Django.

default_page/views.py
from django.shortcuts import get_object_or_404, render
from .models import TreiningTopic
def index(request):
    return render(request, 'default_page/index.html')

def showall(request):
    subjects_trenig = TreiningTopic
    context = {'subjects_trenig': subjects_trenig}
    return render(request, 'default_page/detail.html', context)

def detail(request, subject_id):
    subjects = get_object_or_404(TreiningTopic, pk=subject_id)
    return render(request, 'default_page/detail.html', {'subjects': subjects})

default_page/templates/default_page/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>
        {% block head_title_page %}{% endblock %}
    </title>


</head>
<body>

    {% block content %}


    {% endblock%}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

default_page/templates/default_page/bs_training.html
{% extends "default_page/base.html" %}

    <title>Bootrstap Training</title>

{% block content %}

        <h1>forms dalej</h1>

        <nav class="navbar navbar-expand-sm bg-primary justify-content-center navbar-dark text-center">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Active</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
        </nav>

    <div class="jumbotron text-center">
        <h1><strong>jumbotron text-center</strong></h1>
    </div>

    <div class="container" >
      <div class="row">
        <div class="col-sm-4 text-primary bg-light">
          <h3 class="bg-dark">Column 1</h3>
            <h4 class="text-danger">col-sm-4</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
        </div>
        <div class="col-sm-4 text-success ">
          <h3 class="bg-secondary">Column 2</h3>
            <h4 class="text-danger">col-sm-4</h4>
            <p class="bg-warning">Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
        </div>
        <div class="col-sm-4 text-warning bg-primary">
          <h3>Column 3</h3>
            <h4 class="text-danger">col-sm-4</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
        </div>
      </div>
    </div>

    <div class="container-fluid text-center bg-secondary">
      <h1>container-fluid</h1>
      <div class="row">
        <div class="col" style="background-color:lavender;">.col</div>
        <div class="col" style="background-color:orange;">.col</div>
        <div class="col" style="background-color:lavender;">.col</div>
      </div>
    </div>

    <div class="container">
        <h1>Description Lists</h1>
        <p>The <code>dl</code> element indicates a description list:</p>
      <dl>
        <dt>Coffee</dt>
        <dd>- black hot drink</dd>
        <dt>Milk</dt>
        <dd>- white cold drink</dd>
      </dl>
    </div>

    <div class="container">
      <h2 class="bg-warning">Basic Table</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Favorite programing language</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>John</td>
            <td>Doe</td>
            <td>Python</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Mary</td>
            <td>Moe</td>
            <td>Java</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>July</td>
            <td>Dooley</td>
            <td>C++</td>
            <td>july@example.com</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="container">
        <h1>Button Style</h1>
          <button type="button" class="btn">Basic</button>
          <button type="button" class="btn btn-primary">Primary</button>
          <button type="button" class="btn btn-secondary">Secondary</button>
          <button type="button" class="btn btn-success">Success</button>
          <button type="button" class="btn btn-info">Info</button>
          <button type="button" class="btn btn-warning">Warning</button>
          <button type="button" class="btn btn-danger">Danger</button>
          <button type="button" class="btn btn-dark">Dark</button>
          <button type="button" class="btn btn-light">Light</button>
          <button type="button" class="btn btn-link">Link</button>

        <button type="button" class="btn btn-link">
              <span class="spinner-border spinner-border-sm"></span>
                spiner
          </button>
    </div>

    <div class="container">
      <h2>Colored Spinners</h2>
      <div class="spinner-border text-muted"></div>
      <div class="spinner-border text-primary"></div>
      <div class="spinner-border text-success"></div>
      <div class="spinner-border text-info"></div>
      <div class="spinner-border text-warning"></div>
      <div class="spinner-border text-danger"></div>
      <div class="spinner-border text-secondary"></div>
      <div class="spinner-border text-dark"></div>
      <div class="spinner-border text-light"></div>
    </div>

    <div class="container">
      <h2>Pagination - Active State</h2>
      <p>Add class .active to let the user know which page he/she is on:</p>
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </div>


{% endblock content %}

default_page/templates/default_page/detail.html
<h1>{{ context.trening_topic }}</h1>
<ul>
{% for c in context.choice_set.all %}
    <li>{{ c.trening_topic }}</li>
{% endfor %}
</ul>

default_page/templates/default_page/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

    <h1>Czesc, index.html</h1>

    {% if user.is_authenticated %}
        <a href="{% url 'default_users_app:profile' %}">profile</a>
        <a href="{% url 'default_users_app:logout' %}">logout</a>
    {% else %}
        <a href="{% url 'default_users_app:login' %}">login</a>
        <a href="{% url 'default_users_app:register' %}">register</a>
    {% endif %}

    {% if context %}
    <ul>
    {% for subjects in context %}
            <li><a href="{% url 'default_page:detail' subjects.id %}">{{ context.trening_topic }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No subjects are available.</p>
    {% endif %}

</body>
</html>

default_page/templates/default_page/js_training.html
{% extends 'default_page/base.html' %}

{% block content %}

<h2>My First JavaScript</h2>
    <button type="button"
        onclick="document.getElementById('var_transmiter').innerHTML = Date()">
        Click me to display Date and Time.
    </button>
    <p id="var_transmiter"></p>



{% endblock content %}

default_page/templates/default_page/render_context_in_page.html
{% extends "default_page/base.html" %}

{% block head_title_page %} Render context in page {% endblock %}

{% block content %}

    {{ title }}
    {{ user }}

    {% if user.is_authenticated %}

        <h1>See only user</h1>

        {% for a in my_list %}
            <li>{{ a }}</li>
        {% endfor %}

    {% endif %}

{% endblock %}