default_django/urls.py
from django.contrib import admin
# from django.conf.urls import url, include
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('default_page.urls')),
    path('', include('default_users_app.urls')),
    path('', include('polls.urls')),
    path('', include('training.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('index_question/', views.index_question, name='index_question')
]

training/urls.py
from django.urls import path
from . import views
app_name = 'training'
urlpatterns = [
    path('tindex/', views.t_index, name='t_index'),
    path('t/<int:training_id>/', views.t_detail, name='t_detail'),
]

training/models.py
from django.db import models
from django.utils import timezone
import datetime

class TrainingQuestion(models.Model):
    training_title = models.CharField(max_length=200)
    date_create_trainig = models.DateTimeField('date create training')

    def __str__(self):
        return self.training_title

    def was_published(self):
        return self.date_create_trainig >= timezone.now() - datetime.timedelta(days=1)

training/views.py
from django.shortcuts import get_object_or_404,render
from .models import TrainingQuestion

# Create your views here.
def t_index(request):
    list_trainig = TrainingQuestion.objects.order_by('-date_create_trainig')[:10]
    context = {'list_trainig': list_trainig}
    return render(request, 'training/t_index.html', context)

def t_detail(request, training_id):
    training = get_object_or_404(TrainingQuestion, pk=training_id)
    return render(request, 'training/t_detail.html', {'training': training})

training/templates/training/t_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

        <h1>{{ training.training_title }}</h1>

</body>
</html>

training/templates/training/t_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if list_trainig %}
    {% for training in list_trainig %}
        <li><a href="{% url 'training:t_detail' training.id %}">{{ training.training_title }}</a></li>
    {% endfor %}
{% endif %}


</body>
</html>