default_django/urls.py
from django.contrib import admin
# from django.conf.urls import url, include
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('default_page.urls')),
    path('', include('default_users_app.urls')),
    path('', include('polls.urls')),
    path('', include('training.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('index_question/', views.index_question, name='index_question')
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=20)
    published_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    choice_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=20)
    def __str__(self):
        return self.choice_text



# Dodanie metod __str__() do twoich modeli jest ważne, nie tylko dla twojej własnej wygody, gdy używasz interaktywnego
# prompta, ale także dlatego, że reprezentacje obiektów są używane w automatycznie generowanym panelu administracyjnym Django.

polls/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Question
from django.http import Http404
from django.template import loader



def detail(request, question_id):
    # return HttpResponse("You're looking at question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/question_id.html", {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def index_question(request):
    latest_question_list = Question.objects.order_by('-published_date')[:5]
    # template = loader.get_template('polls/polls_index.html')
    context_question = {
        'latest_question_list': latest_question_list
    }
    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(template.render(context_question, request))
    return render(request, 'polls/index_question.html', context_question)

polls/templates/polls/index_question.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <l1>
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            </l1>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are avaible.</p>
{% endif %}

polls/templates/polls/polls_index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <l1>
                <a href="/polls/{{ question.id}}/">{{ question.question_text }}</a>
            </l1>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are avaible.</p>
{% endif %}

polls/templates/polls/question_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
        </ul>


</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>